### PR TITLE
Add ECCV-2018-RCAN

### PR DESCRIPTION
**Pull request by yulunzhang**
add rcan.py in code/model
add options for RCAN in options.py
add training scripts for RCAN in demo.py

### CODE REVIEW

**Comment by suke27** [comment]
what is RCAN?

**Comment by thstkdgus35** [comment]
Thank you for your contribution! It looks fine.

**Comment by freesouls** [comment]
@yulunzhang  the pretrain model of RCAN link in dropbox [https://www.dropbox.com/s/mjbcqkd4nwhr6nu/models_ECCV2018RCAN.zip?dl=0](https://www.dropbox.com/s/mjbcqkd4nwhr6nu/models_ECCV2018RCAN.zip?dl=0) seems not valid, saying “(该文件已不在此处) the files was not here”, please update the link, thanks in advance!!!

**Comment by freesouls** [comment]
@yulunzhang  fixed, I find valid links in your origin git repo [https://github.com/yulunzhang/RCAN](https://github.com/yulunzhang/RCAN), sorry to bother!

**Pull request merged**
